import type { SupportedLanguage } from '@/types/user.types';
import type { ElectionRegion } from '@/types/election.types';

export const ELECTION_REGIONS: ElectionRegion[] = [
  {
    id: 'maharashtra',
    name: 'Maharashtra',
    state: 'Maharashtra',
    defaultLanguage: 'mr',
    languages: ['mr', 'hi', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2025-11-15',
    registrationDeadline: '2025-10-25',
    constituency: 'Mumbai North',
    helplineNumber: '1950',
  },
  {
    id: 'karnataka',
    name: 'Karnataka',
    state: 'Karnataka',
    defaultLanguage: 'kn',
    languages: ['kn', 'en', 'hi'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2026-04-30',
    registrationDeadline: '2026-03-31',
    constituency: 'Bangalore South',
    helplineNumber: '1950',
  },
  {
    id: 'tamil_nadu',
    name: 'Tamil Nadu',
    state: 'Tamil Nadu',
    defaultLanguage: 'ta',
    languages: ['ta', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2026-05-01',
    registrationDeadline: '2026-04-01',
    constituency: 'Chennai Central',
    helplineNumber: '1950',
  },
  {
    id: 'andhra_pradesh',
    name: 'Andhra Pradesh',
    state: 'Andhra Pradesh',
    defaultLanguage: 'te',
    languages: ['te', 'en', 'hi'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2026-05-01',
    registrationDeadline: '2026-04-01',
    constituency: 'Vijayawada',
    helplineNumber: '1950',
  },
  {
    id: 'west_bengal',
    name: 'West Bengal',
    state: 'West Bengal',
    defaultLanguage: 'bn',
    languages: ['bn', 'hi', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2026-04-27',
    registrationDeadline: '2026-03-27',
    constituency: 'Kolkata North',
    helplineNumber: '1950',
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    state: 'Gujarat',
    defaultLanguage: 'gu',
    languages: ['gu', 'hi', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2027-02-01',
    registrationDeadline: '2027-01-01',
    constituency: 'Ahmedabad East',
    helplineNumber: '1950',
  },
  {
    id: 'kerala',
    name: 'Kerala',
    state: 'Kerala',
    defaultLanguage: 'ml',
    languages: ['ml', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2026-04-25',
    registrationDeadline: '2026-03-25',
    constituency: 'Thiruvananthapuram',
    helplineNumber: '1950',
  },
  {
    id: 'uttar_pradesh',
    name: 'Uttar Pradesh',
    state: 'Uttar Pradesh',
    defaultLanguage: 'hi',
    languages: ['hi', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2027-02-10',
    registrationDeadline: '2027-01-10',
    constituency: 'Lucknow',
    helplineNumber: '1950',
  },
  {
    id: 'delhi',
    name: 'Delhi',
    state: 'Delhi',
    defaultLanguage: 'hi',
    languages: ['hi', 'en', 'mr'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2025-02-05',
    registrationDeadline: '2025-01-06',
    constituency: 'New Delhi',
    helplineNumber: '1950',
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    state: 'Rajasthan',
    defaultLanguage: 'hi',
    languages: ['hi', 'en'],
    registrationPortal: 'https://voters.eci.gov.in',
    electionDate: '2028-11-01',
    registrationDeadline: '2028-10-01',
    constituency: 'Jaipur',
    helplineNumber: '1950',
  },
];

export const REGION_BY_ID = new Map<string, ElectionRegion>(
  ELECTION_REGIONS.map((r) => [r.id, r])
);

/** Derive default language for a browser locale string */
export function getDefaultLanguageForLocale(locale: string): SupportedLanguage {
  const map: Record<string, SupportedLanguage> = {
    hi: 'hi',
    ta: 'ta',
    te: 'te',
    bn: 'bn',
    mr: 'mr',
    kn: 'kn',
    gu: 'gu',
    ml: 'ml',
  };
  const lang = locale.split('-')[0].toLowerCase();
  return map[lang] ?? 'en';
}
